name: Pandoc

on:
  push:
    branches: [main]

jobs:
  printenv:
    runs-on: ubuntu-latest

    steps:
      - name: Print environment
        run: |
          env | grep HOME

  setenv:
    needs: printenv
    runs-on: ubuntu-latest

    steps:
      - name: Set up Pandoc
        uses: docker://pandoc/latex:latest

      - name: Check environment setup
        run: |
          docker version --format '{{.Server.Version}}'
          docker run pandoc/latex:latest --version | grep ^pandoc
          docker exec container env | grep DOCKER

  build:
    needs: setenv
    runs-on: ubuntu-latest
    #if: "(    github.event_name == 'pull_request'
    #       && !contains(github.event.pull_request.body, '[skip ci]')
    #       && !contains(github.event.pull_request.body, '[skip docs]')
    #     )
    #     || contains(github.event.ref, 'pandoc')
    #     || contains(github.event.ref, 'master')"

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Generate PDF reference documentation
        run: |
          echo ./pandoc/md2pdf reference
