name: Pandoc

on:
  push:
    branches: [main]

jobs:
  printenv:
    runs-on: ubuntu-latest

    steps:
      - name: Print Ubuntu environment
        run: |
          env | grep GIT
          env | grep HOME
          docker version --format '{{.Server.Version}}'
          #docker run pandoc/latex:latest --version | grep ^pandoc

  build:
    needs: printenv
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest
    #if: "(    github.event_name == 'pull_request'
    #       && !contains(github.event.pull_request.body, '[skip ci]')
    #       && !contains(github.event.pull_request.body, '[skip docs]')
    #     )
    #     || contains(github.event.ref, 'pandoc')
    #     || contains(github.event.ref, 'master')"

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Print Pandoc environment
        run: |
          #env | grep TEX
          pandoc --version | grep ^pandoc

      - name: Install additional TeX fonts
        run: |
          find . -name install-tex-fonts
          chmod u+x ./pandoc/extras/install-tex-fonts
          DEBUG=1 & ./pandoc/extras/install-tex-fonts

      - name: Generate PDF reference documentation
        run: |
          find . -name md2pdf
          chmod u+x ./pandoc/md2pdf
          DEBUG=1 & ./pandoc/md2pdf reference
